using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Text;
using JsonParser.App.TokenModel;

namespace JsonParser.App.Lexer;

public sealed class LexerOutput
{
    private readonly StringBuilder _lexemeBuffer = new();
    private readonly List<Token> _generatedTokens = [];
    private readonly ReadOnlyCollection<Token> _readonlyGeneratedTokens;

    public LexerOutput() => _readonlyGeneratedTokens = _generatedTokens.AsReadOnly();

    /// <summary>
    /// Gets the list of tokens generated by the lexer.
    /// </summary>
    public IReadOnlyList<Token> GeneratedTokens => _readonlyGeneratedTokens;

    /// <summary>
    /// Appends a character to the lexeme buffer.
    /// </summary>
    /// <param name="character">The character to append to the lexeme buffer.</param>
    public void Append(char character) => _lexemeBuffer.Append(character);

    /// <summary>
    /// Appends a string to the lexeme buffer.
    /// </summary>
    /// <param name="text">The string to append to the lexeme buffer.</param>
    public void Append(string text)
    {
        ArgumentException.ThrowIfNullOrEmpty(text);

        _lexemeBuffer.Append(text);

        Debug.Assert(_lexemeBuffer.Length > 0, "Lexeme buffer should not be empty after appending text.");
    }

    /// <summary>
    /// Emits a token with the specified type, value, and starting index.
    /// </summary>
    /// <param name="tokenType">The type of the token to emit.</param>
    /// <param name="value">The value of the token to emit.</param>
    /// <param name="tokenStartIndex">The starting index of the token in the input buffer.</param>
    public void Emit(TokenType tokenType, string value, int tokenStartIndex)
    {
        ArgumentException.ThrowIfNullOrEmpty(value);
        ArgumentOutOfRangeException.ThrowIfLessThan(tokenStartIndex, 0);

        _generatedTokens.Add(new Token(tokenType, value, tokenStartIndex));
    }

    /// <summary>
    /// Emits a token with the specified type and the current contents of the lexeme buffer
    /// and clears the buffer.
    /// </summary>
    /// <param name="tokenType"></param>
    /// <param name="tokenStartIndex"></param>
    public void EmitBufferedToken(TokenType tokenType, int tokenStartIndex)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(tokenStartIndex, 0);

        Debug.Assert(_lexemeBuffer.Length > 0, "Cannot emit a token with an empty lexeme buffer.");

        var value = _lexemeBuffer.ToString();
        Emit(tokenType, value, tokenStartIndex);

        _lexemeBuffer.Clear();
    }

    /// <summary>
    /// Asserts that the lexeme buffer is empty, indicating that no unprocessed characters remain
    /// in the buffer after the lexer has finished processing the input.
    /// </summary>
    public void AssertInvariant()
        => Debug.Assert(_lexemeBuffer.Length == 0, $"End of input while reading token: {_lexemeBuffer}");
}